# caetra configuration file

[logging]
level = "DEBUG"

[shields]

all = true

#[shields.usb]
#notify = true

[senders]

[senders.canarytokens]
enable = true
token = "gz9fyvwq1qs7r9etclwp42kio.canarytokens.com"

[senders.telegram]
enable = false

