# caetra configuration file

[caetra]
machine = "TheArch"
# list of enabled shields; this will override shield configuration
shields_enabled = ["hid_move"]

[logging]
level = "DEBUG"

[senders.canarytokens]
enable = false
token = "gz9fyvwq1qs7r9etclwp42kio.canarytokens.com"

[senders.telegram]
enable = false 
chat_id = 35983972
bot_api_key = "8245667438:AAHIANeASwTh_PviZUl62xOnlHwR469M4B4"
