# this is the configuration file related with Caetra's ambient_light Shield
# add here all the user configurable parameters to tune the
# behaviour of the shield

# Name of the Caetra Shield and generic config values
# case sensitive must match with SHIELD_NAME on python side
[ambient_light]

# if this shield is enable 
enable = true 


# a description that will logged
description = "Triggers when the ambient light changes, this could means that someone is around the machine"


# label to describe what happen on physical world
action_label = "ambient light changed"


# to configure special features
[ambient_light.features]

# the feature variable 
limit_sending = true
max_actions = 2
# time in seconds to start sending notifications again
cool_down_time = 10





