# this is the configuration file related with Caetra's USB Shield
# add here all the user configurable parameters to tune the
# behaviour of the shield, e.g. if will de-authorize a device or not

# Name of the Caetra Shield and generic config values
# case sensitive must match with SHIELD_NAME on python side
[usb]

# if this shield is enable (if false will override the main config)
enable = true 

# a description that will logged
description = "When a USB device is attached will do several things"

# this will override the general senders configuration
[usb.senders.canarytokens]
enable = true
token = "gz9fyvwq1qs7r9etclwp42kio.canarytokens.com"

de_authorize_dev = false
